# Generated by Django 5.2.6 on 2025-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottype',
            name='size_rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='Relative size rank used for compatibility checks. For example: Simple=1, Extended=2, Oversize=3.'),
        ),
    ]
