# Generated by Django 5.2.6 on 2025-11-26 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_slottype_size_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
