# Generated by Django 5.2.6 on 2025-11-27 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('parking', '0004_alter_gate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(db_index=True, max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('exit_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occasional_tickets', to='parking.parkingslot')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
