# Generated by Django 5.2.6 on 2025-11-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_credit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customerbase',
            managers=[
            ],
        ),
    ]
