# Generated by Django 5.2.6 on 2025-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_managers_alter_customerbase_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ssn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
