# Generated by Django 5.2.6 on 2025-11-24 21:57

import customers.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_billing_info_customer_ssn'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', customers.managers.CustomerManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customerbase',
            managers=[
                ('objects', customers.managers.CustomerManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_info',
            field=models.TextField(blank=True, help_text='Optional billing information.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.FloatField(blank=True, help_text='Optional customer credit balance.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ssn',
            field=models.CharField(blank=True, help_text='SSN or equivalent identifier.', max_length=50),
        ),
    ]
