# Generated by Django 5.2.6 on 2025-11-13 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['license_plate'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='accessibility_requirements',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='height',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='length',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='requires_oversize',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='width',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the vehicle was registered.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_disability_permit',
            field=models.BooleanField(default=False, help_text='True if the vehicle is allowed to use accessible slots with special pricing.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_oversize',
            field=models.BooleanField(default=False, help_text='True if this vehicle requires an oversize slot.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(help_text='Unique license plate identifier used at the gate.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(help_text='Customer who owns this vehicle.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
