# Generated by Django 5.2.6 on 2025-11-24 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_gate'),
        ('vehicles', '0002_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_oversize',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='minimum_slot_type',
            field=models.ForeignKey(blank=True, help_text='Minimum slot type this vehicle requires (e.g. Simple, Extended, Oversize). This should use the same SlotType records as ParkingSlot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='parking.slottype'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable UUID primary key for the vehicle.', primary_key=True, serialize=False),
        ),
    ]
